### ISSUE TITLE
Honorable mention? `dsq`

### ISSUE THREAD

**Issue by jtagcat** [fiatjaf/awesome-jq#23]
https://github.com/multiprocessio/dsq

> Commandline tool for running SQL queries against JSON, CSV, Excel, Parquet, and more. 

> `$ dsq testdata.json "SELECT * FROM {} WHERE x > 10"`

It isn't jq really, but it's similar.

**Comment by fiatjaf** [comment]
This list is strictly for jq things, but `dsq` would be great on https://github.com/burningtree/awesome-json.

**Comment by jtagcat** [comment]
A thing I came looking for, searching 'html': https://github.com/mgdm/htmlq (adding for search)
